//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public string SOATO { get; set; }
        public string NAME { get; set; }
        public string OBL { get; set; }
        public string RAION { get; set; }
        public string SOVET { get; set; }
        public string TIP { get; set; }
        public string GNI { get; set; }
        public Nullable<System.DateTime> DATAV { get; set; }
        public string SOATON { get; set; }
        public string DATEL { get; set; }
        public string MAL { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
