//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string MaidenName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string BirthplaceId { get; set; }
        public bool IsClientResidentRB { get; set; }
        public bool IsClientCitizenRB { get; set; }
        public string SeriesNumberIdentityDoc { get; set; }
        public string PersonalNumber { get; set; }
        public string IssuedIdentityDoc { get; set; }
        public System.DateTime DateIssueIdentityDoc { get; set; }
        public System.DateTime ValidityIdentityDoc { get; set; }
        public string SurnameLat { get; set; }
        public string NameLat { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
    
        public virtual City City { get; set; }
    }
}
